"""Generate deploy/10-rbac.yaml: one ServiceAccount per agent, least privilege.

    python deploy/generate_rbac.py   (edit WATCHED below, then re-run)

| agent    | aiops-system (CRDs)                           | watched namespaces            |
|----------|-----------------------------------------------|-------------------------------|
| monitor  | create Incidents, read Remediations/Lessons    | read pods, logs, events, apps |
| diagnose | read Incidents, create Remediations, read Lessons | nothing                   |
| repair   | update Remediations/Incidents                 | patch Deployments, read RS/pods |
| validate | update Remediations/Incidents, write Lessons   | read Deployments, RS, pods    |
"""
import os

WATCHED = ["aiops-demo", "travel", "github"]
SYSTEM = "aiops-system"
G = "aiops.homelab.dev"

SYSTEM_RULES = {
    "monitor": [
        ([G], ["incidents"], ["get", "list", "create", "delete"]),
        ([G], ["incidents/status"], ["get", "patch"]),
        ([G], ["remediations", "lessons"], ["get", "list"]),  # read-only console
    ],
    "diagnose": [
        ([G], ["incidents"], ["get", "list"]),
        ([G], ["incidents/status"], ["get", "patch"]),
        ([G], ["remediations"], ["get", "list", "create"]),
        ([G], ["remediations/status"], ["get", "patch"]),
        ([G], ["lessons"], ["get", "list"]),
    ],
    "repair": [
        ([G], ["remediations"], ["get", "list"]),
        ([G], ["remediations/status"], ["get", "patch"]),
        ([G], ["incidents"], ["get"]),
        ([G], ["incidents/status"], ["get", "patch"]),
    ],
    "validate": [
        ([G], ["remediations"], ["get", "list"]),
        ([G], ["remediations/status"], ["get", "patch"]),
        ([G], ["incidents"], ["get"]),
        ([G], ["incidents/status"], ["get", "patch"]),
        ([G], ["lessons"], ["get", "list", "create", "patch"]),
    ],
}
WATCHED_RULES = {
    "monitor": [
        ([""], ["pods", "pods/log", "events"], ["get", "list"]),
        (["apps"], ["deployments", "replicasets"], ["get", "list"]),
    ],
    "repair": [
        (["apps"], ["deployments"], ["get", "list", "watch", "patch"]),
        (["apps"], ["replicasets"], ["get", "list", "watch"]),
        ([""], ["pods"], ["get", "list"]),
    ],
    "validate": [
        (["apps"], ["deployments", "replicasets"], ["get", "list", "watch"]),
        ([""], ["pods"], ["get", "list"]),
    ],
}


def rules_yaml(rules):
    out = []
    for groups, resources, verbs in rules:
        out.append(f"  - apiGroups: {groups!r}\n    resources: {resources!r}\n    verbs: {verbs!r}".replace("'", '"'))
    return "\n".join(out)


def role(name, namespace, rules, agent):
    return f"""apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {name}
  namespace: {namespace}
rules:
{rules_yaml(rules)}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {name}
  namespace: {namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {name}
subjects:
  - kind: ServiceAccount
    name: aiops-{agent}
    namespace: {SYSTEM}"""


docs = ["# Generated by deploy/generate_rbac.py - one ServiceAccount per agent, least privilege."]
for agent in SYSTEM_RULES:
    docs.append(f"""apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-{agent}
  namespace: {SYSTEM}""")
    docs.append(role(f"aiops-{agent}", SYSTEM, SYSTEM_RULES[agent], agent))
    for ns in WATCHED:
        if agent in WATCHED_RULES:
            docs.append(role(f"aiops-v2-{agent}", ns, WATCHED_RULES[agent], agent))

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "10-rbac.yaml")
with open(path, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(docs[0] + "\n" + "\n---\n".join(docs[1:]) + "\n")
print("wrote", path)
